baseURL = "https://jamvie.net/"
languageCode = "en-us"
title = "Jamvie: CTF writeups and more"
theme = "casper3" 
author = "Jam Polintan"
enableInlineShortcodes = true
footnoteReturnLinkContents = "↩"

[params]
github = "https://github.com/jamiepoli"
description = "A blog about Capture the Flag competitions from a software dev who does it for fun."
mainSections = ["posts"]
profile = "https://jamiepoli.github.io/img/profile.png"



[taxonomies]
tags = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/tags/writeups"
    weight = 10
    [[menu.main]]
    identifier = "miscellaneous"
    name = "Misc"
    url = "/tags/misc"
    weight = 10



