baseURL = "https://jamvie.net/"
languageCode = "en-us"
title = "Jamvie: CTF writeups and more"
theme = "casper3" 
author = "Jam Polintan"


[params]
github = "https://github.com/jamiepoli"
description = "A blog about Capture the Flag competitions from a software dev who does it for fun."
mainSections = ["posts"]
profile = "https://jamiepoli.github.io/img/profile.png"


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10



[taxonomies]
tag = "tags"