baseURL = "https://jamvie.net/"
title = "Jamvie: CTF writeups and more"
theme = "newsroom" 
author = "Jam Polintan"
paginate = 5
DefaultContentLanguage = "en"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]
github = "https://github.com/jamiepoli"
description = "A blog about Capture the Flag competitions from a software dev who does it for fun."
mainSections = ["posts"]



[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/tags/writeups"
    weight = 10
    [[menu.main]]
    identifier = "miscellaneous"
    name = "Misc"
    url = "/tags/misc"
    weight = 10



